### ISSUE TITLE
(JS-0242) Use `const` declarations for variables that are never reassigned.

### ISSUE THREAD

**Issue by SamsShow** [SamsShow/ImageSearch#1]
## Description
Variables that are never re-assigned a new value after their initial declaration should be declared with the `const` keyword. This prevents the programmer from erroneously re-assigning to a read-only variable and informs those reading the code that a variable is a constant value.

## Occurrences
There is 1 occurrence of this issue in the repository.

**Comment by Pariharx7** [comment]
Hey, I'm learning JS. 
Can me assign me this issue.

**Comment by SamsShow** [comment]
@Pariharx7 ok
