### ISSUE TITLE
[fix]: Empty Search

### ISSUE THREAD

**Issue by SamsShow** [SamsShow/ImageSearch#2]
While performing an empty search it shows a blank output

![image](https://github.com/SamsShow/ImageSearch/assets/74039834/1de43d39-f50a-4333-ad53-a7aea2ca845f)

But it should return the initial results:
![Screenshot from 2023-10-10 16-05-53](https://github.com/SamsShow/ImageSearch/assets/74039834/5a20aed0-43f5-4ffc-9c8f-8296ae5b9e89)

**Comment by harshkushwaha2001** [comment]
hi @SamsShow i would like work on this issue , as I have good knowledge of JavaScript,
I am sure I can fix it.
so please assign me.
favour :) can you put Hacktoberfest-accepted label on it

**Comment by SamsShow** [comment]
@harshkushwaha2001 ok you can work
